logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube-Stable]
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended (Stable)"
build-mode = "both"                                                           # 'both', 'apk' or 'module'
allow-alpha-version = true                                                    # allow downloading alpha versions from apkmirror
excluded-patches = "custom-branding-icon-afn-red custom-branding-name bypass-ambient-mode-restrictions change-homepage custom-branding-icon-afn-blue custom-branding-icon-mmt custom-branding-icon-revancify-blue custom-double-tap-length custom-package-name custom-video-speed disable-hdr-video custom-seekbar-color disable-haptic-feedback disable-startup-shorts-player enable-tablet-miniplayer disable-quic-protocol disable-landscape-mode enable-tablet-miniplayer enable-wide-searchbar enable-timestamps-speed enable-tablet-navigation-bar force-vp9-codec hide-account-menu hide-double-tap-overlay-filter hide-player-overlay-filter hide-search-terms hide-seekbar hide-seek-message hide-shorts-component theme overlay-buttons microg-support"        # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "materialyou force-premium-heading"                        # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                              # 'auto', 'latest', 'beta' or a custom one like '17.45.36'
exclusive-patches = false                                                     # excludes all patches by default
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvx-magisk"

[YouTube-Latest]
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended (Latest)"
build-mode = "both"                                                           # 'both', 'apk' or 'module'
allow-alpha-version = true                                                    # allow downloading alpha versions from apkmirror
excluded-patches = "custom-branding-icon-afn-red custom-branding-name"        # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "materialyou force-premium-heading"                        # space-seperated patches to include (non-excluded patches are included by default)
version = "latest"                                                            # 'auto', 'latest', 'beta' or a custom one like '17.45.36'
exclusive-patches = false                                                     # excludes all patches by default
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvx-magisk"

[Music]
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended (Music)"
build-mode = "both"
allow-alpha-version = true
excluded-patches = "custom-branding-music-afn-red"
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-magisk"
arch = "both"
